# Generated by Django 4.1.7 on 2023-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carerecipient",
            name="nhs_number",
        ),
        migrations.AlterField(
            model_name="carerecipient",
            name="subscription_id",
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
