# Generated by Django 4.1.7 on 2023-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management_interface", "0002_remove_carerecipient_nhs_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carerecipient",
            name="nhs_number_hash",
            field=models.CharField(
                db_index=True, editable=False, max_length=128, unique=True
            ),
        ),
    ]
